apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backendsvc
  template:
    metadata:
      labels:
        app: backendsvc
    spec:
      containers:
        - name: backend
          image: kanwarsaad/doctorbackend:3
          ports:
            - containerPort: 5000
