apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backendsvc
  template:
    metadata:
      labels:
        app: backendsvc
    spec:
      containers:
        - name: backend
          image: kanwarsaad/doctorbackend:2
          env:
            - name: MONGODB_URI
              value: "mongodb://shop:shop@mongo-service:27017"
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
